project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    # theme: cosmo
    theme: readable
    # theme: flatly
    # theme: litera
    highlight: github
    css: styles.css



