project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - posts/**

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zzsi
      - icon: linkedin
        href: https://www.linkedin.com/in/zhangzhangsi/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    # theme: cosmo
    theme: readable
    # theme: flatly
    # theme: litera
    highlight: github
    css: styles.css



